---
defaultBaseImage: cgr.dev/chainguard/static:latest
builds:
  - id: machinery-status-collector
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/stuttgart-things/machinery-status-collector/cmd.Version={{.Env.VERSION}}
      - -X github.com/stuttgart-things/machinery-status-collector/cmd.Commit={{.Env.COMMIT}}
      - -X github.com/stuttgart-things/machinery-status-collector/cmd.Date={{.Env.DATE}}
